steps:
  - label: ":hammer: Install Node.js and npm"
    command: |
      curl -sL https://deb.nodesource.com/setup_16.x | bash -
      apt-get install -y nodejs
  - label: ":yarn: Install Yarn"
    command: |
      npm install --global yarn
  - label: ":hammer: Install dependencies"
    command: yarn install && yarn build

  #  command: "scripts/build.sh"
  #   key: build

  # - label: ":test_tube: Testt"
  #   command: "scripts/test.sh"
  #   key: test
  #   depends_on: build

  # - label: ":rocket: Deployy :rocket:"
  #   command: "scripts/deploy.sh"
  #   key: deployyy
  #   depends_on: test
