steps:
  - label: ":hammer: :hammer: Buildd"
    command: echo "Hello buildkite"
    command: buildkite-agent annotate --style 'info' 'annotate hello world'
  - label: ":hammer: Install dependencies"
    command: |
      curl -o- -L https://yarnpkg.com/install.sh | bash
      export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - label: ":hammer: :hammer: Buildd"
    command: |
      echo "Hello buildkite"
      echo "Hello!"
      buildkite-agent annotate --style 'info' 'annotate hello world'
      echo " ___ building next"
      yarn build

  #  command: "scripts/build.sh"
  #   key: build

  # - label: ":test_tube: Testt"
  #   command: "scripts/test.sh"
  #   key: test
  #   depends_on: build

  # - label: ":rocket: Deployy :rocket:"
  #   command: "scripts/deploy.sh"
  #   key: deployyy
  #   depends_on: test
