steps:
  - label: ":hammer: :hammer: Buildd"
    command: echo "Hello buildkite"
    command: echo "Hello!"
    command: buildkite-agent annotate --style 'info' 'annotate hello world'
  #  command: "scripts/build.sh"
  #   key: build

  # - label: ":test_tube: Testt"
  #   command: "scripts/test.sh"
  #   key: test
  #   depends_on: build

  # - label: ":rocket: Deployy :rocket:"
  #   command: "scripts/deploy.sh"
  #   key: deployyy
  #   depends_on: test
