steps:
  - label: ":hammer: :hammer: Buildd"
  - label: ":hammer: Install Node.js and npm"
    command: |
      curl -sL https://deb.nodesource.com/setup_14.x | bash -
      apt-get install -y nodejs
  - label: ":hammer: Install dependencies"
    command: npm install && npm build

  #  command: "scripts/build.sh"
  #   key: build

  # - label: ":test_tube: Testt"
  #   command: "scripts/test.sh"
  #   key: test
  #   depends_on: build

  # - label: ":rocket: Deployy :rocket:"
  #   command: "scripts/deploy.sh"
  #   key: deployyy
  #   depends_on: test
